# Generated by Django 6.0.3 on 2026-04-04 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced/Separated')], default='single', max_length=20)),
                ('family_members', models.PositiveIntegerField(default=1)),
                ('dependents', models.PositiveIntegerField(default=0)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('existing_savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('existing_loans', models.JSONField(default=list)),
                ('life_goals', models.JSONField(default=list)),
                ('goals_detail', models.JSONField(default=dict)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='life_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
