# Generated by Django 6.0.3 on 2026-04-04 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('mutual_fund', 'Mutual Fund'), ('etf', 'ETF'), ('crypto', 'Cryptocurrency'), ('fd', 'Fixed Deposit'), ('gold', 'Gold'), ('ppf', 'PPF / NPS'), ('bonds', 'Bonds / Debt'), ('real_estate', 'Real Estate'), ('other', 'Other')], default='stock', max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
