# Generated by Django 6.0.3 on 2026-03-31 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('full_report', models.TextField()),
                ('tickers', models.JSONField(default=list)),
                ('market_snapshot', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='agents.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
