# Generated by Django 6.0.3 on 2026-03-31 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('preference', 'User Preference Snapshot'), ('recommendation', 'Past Recommendation'), ('market_event', 'Market Event'), ('interaction', 'User Interaction')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('embedding_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
